@startuml
class UpgradeSelectorPresenter {
    + UpgradeSelectorPresenter(model:UpgradeSelector, view:UpgradeSelectorView)
    + PostInitialize() : void
}
IPostInitializable <|-- UpgradeSelectorPresenter
@enduml
