@startuml
class UpgradeManager {
    + Initialize(upgradeCollection:UpgradeCollection) : void
    + ApplyAllUpgrades() : void
    + AddUpgrade(upgradeId:UpgradeId) : void
}
MonoBehaviour <|-- UpgradeManager
@enduml
