@startuml
class Health {
    + MaxHealth : float <<get>>
    + Initialize(maxHealth:float) : void
    + ResetHealth(maxHealth:float) : void
}
class "ReadOnlyReactiveProperty`1"<T> {
}
MonoBehaviour <|-- Health
Health --> "CurrentHealth<float>" "ReadOnlyReactiveProperty`1"
Health --> "InitializedAsync" UniTask
@enduml
