@startuml
class PlayerDispatcher {
    + PlayerDispatcher(playerProvider:PlayerProvider, playerPresenter:PlayerPresenter)
    + PostInitialize() : void
}
IPostInitializable <|-- PlayerDispatcher
@enduml
