@startuml
class Battle {
    + UpgradablePlayerId : int <<get>>
    + SetState(state:BattleState) : void
    + SetUpgradablePlayer(playerId:int) : void
}
enum BattleState {
    Start,
    Battle,
    Upgrade,
    End,
}
class "ReactiveProperty`1"<T> {
}
MonoBehaviour <|-- Battle
Battle o-> "State<BattleState>" "ReactiveProperty`1"
Battle +-- BattleState
@enduml
